import {NextRequest} from 'next/server';
import {z} from 'zod';
import {db,runtime} from '@/lib/db';
import {filterSchema,clinicDate,clinicTime,dateSchema} from '@/lib/contracts';
import {serverInterpret,modelConfig} from '@/lib/assistant';
import {HttpError,settings,search,saveAppointment,getAppointment,updatePatient,saveSettings,seedSamples} from '@/lib/service';
export const dynamic='force-dynamic';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
async function route(req:NextRequest){try{const user=req.headers.get('oai-authenticated-user-id'),email=req.headers.get('oai-authenticated-user-email');if(!user||!email)return json({error:'Sign in to access clinic records.',code:'UNAUTHENTICATED'},401);const actor=email;const url=new URL(req.url);const path=url.pathname.replace(/^\/api\/v1\/?/,'').split('/');const database=db();
 let body:any; if(req.method!=='GET'){const origin=req.headers.get('origin');if(origin&&origin!==url.origin)throw new HttpError(403,'Cross-origin writes are not allowed');if(req.headers.get('sec-fetch-site')==='cross-site')throw new HttpError(403,'Cross-origin writes are not allowed');if(!req.headers.get('content-type')?.includes('application/json'))throw new HttpError(415,'JSON is required');const raw=await req.text();if(raw.length>24000)throw new HttpError(413,'Request too large');try{body=JSON.parse(raw)}catch{throw new HttpError(400,'Invalid JSON')}}
 if(req.method==='GET'&&path[0]==='meta'){const data=await database.batch([database.prepare('SELECT COUNT(*) AS n FROM patients'),database.prepare('SELECT open,close,capacity,version FROM clinic_settings WHERE id=1')]);return json({settings:data[1].results[0]||await settings(database),user:{id:user,email},today:clinicDate(),now:clinicTime(),timezone:'Asia/Bangkok',patientCount:(data[0].results[0] as any).n,serverModel:!!modelConfig(runtime())})}
 if(req.method==='GET'&&path[0]==='availability'){const date=dateSchema.parse(url.searchParams.get('date'));const exclude=url.searchParams.get('exclude')||'';const counts=await database.prepare("SELECT time,COUNT(*) AS n FROM appointments WHERE date=? AND id!=? AND status NOT IN ('cancelled','no_show') GROUP BY time").bind(date,exclude).all();return json({counts:Object.fromEntries(counts.results.map((r:any)=>[r.time,r.n]))})}
 if(req.method==='GET'&&path[0]==='patients'){if(path[1]){const p=await database.prepare('SELECT * FROM patients WHERE id=?').bind(path[1]).first();if(!p)throw new HttpError(404,'Patient not found');return json({patient:p,history:(await database.prepare('SELECT id,date,time,service,followup,status,remarks FROM appointments WHERE patient_id=? ORDER BY date DESC,time DESC LIMIT 100').bind(path[1]).all()).results})}const q=(url.searchParams.get('q')||'').slice(0,120);if(!q)return json({patients:[]});const term='%'+q.replace(/[\\%_]/g,'\\$&')+'%';return json({patients:(await database.prepare("SELECT id,hn,name,dob,sex,version FROM patients WHERE hn LIKE ? ESCAPE '\\' OR name LIKE ? ESCAPE '\\' ORDER BY CASE WHEN hn=? THEN 0 ELSE 1 END,name LIMIT 20").bind(term,term,q.toUpperCase()).all()).results})}
 if(req.method==='PATCH'&&path[0]==='patients'&&path[1])return json(await updatePatient(database,path[1],body,actor));
 if(req.method==='POST'&&path[0]==='appointments'&&path[1]==='search'){const parsed=z.object({filters:filterSchema,offset:z.number().int().min(0).max(100000).default(0)}).strict().parse(body);return json(await search(database,parsed.filters,parsed.offset))}
 if(req.method==='POST'&&path[0]==='appointments'&&!path[1])return json(await saveAppointment(database,body,actor),201);
 if(req.method==='PATCH'&&path[0]==='appointments'&&path[1])return json(await saveAppointment(database,body,actor,path[1]));
 if(req.method==='GET'&&path[0]==='appointments'&&path[1])return json(await getAppointment(database,path[1]));
 if(req.method==='PATCH'&&path[0]==='settings')return json(await saveSettings(database,body,actor));
 if(req.method==='POST'&&path[0]==='examples')return json(await seedSamples(database,actor));
 if(req.method==='POST'&&path[0]==='assistant'){const input=z.object({query:z.string().trim().min(1).max(2000),quick:z.boolean().optional()}).strict().parse(body);return json(await serverInterpret(input.query,input.quick?{}:runtime()))}
 if(req.method==='GET'&&path[0]==='events'){const after=Math.max(0,Number(url.searchParams.get('after')||0)||0);const entity=url.searchParams.get('entityId');const data=entity?await database.prepare('SELECT sequence,id,type,entity_id AS entityId,actor,at FROM events WHERE entity_id=? ORDER BY sequence DESC LIMIT 30').bind(entity).all():await database.prepare('SELECT sequence,id,type,entity_id AS entityId,actor,at FROM events WHERE sequence>? ORDER BY sequence LIMIT 100').bind(after).all();return json({events:data.results,nextCursor:data.results.length?data.results[data.results.length-1].sequence:after})}
 return json({error:'Not found'},404);
 }catch(e:any){if(e instanceof z.ZodError)return json({error:e.issues.map((i:any)=>i.path.join('.')+': '+i.message).join('; ')},400);if(e instanceof HttpError)return json({error:e.message},e.status);const message=String(e?.message||e);if(message.includes('SLOT_FULL'))return json({error:'This time slot is full. Choose another slot.'},409);if(message.includes('DUPLICATE_VISIT')||message.includes('appointments.patient_id, appointments.date, appointments.time'))return json({error:'This patient already has a booking at this time.'},409);if(message.includes('OUTSIDE_HOURS'))return json({error:'Choose a time within clinic hours.'},409);if(message.includes('patients.hn'))return json({error:'This HN already exists. Look up and select the existing patient.'},409);if(message.includes('SETTINGS_CONFLICT'))return json({error:'Existing bookings conflict with these settings.'},409);console.error('Clinic request failed',e?.name||'Error');return json({error:pathSafeError(req.url,message)},503)}}
function pathSafeError(url:string,message:string){return url.includes('/assistant')&&!message.includes('D1')?'The assistant could not interpret that request. Try Quick search or the filters.':'Unable to save or load clinic data. Please retry; your form has been kept.'}
export {route as GET,route as POST,route as PATCH};
