import type {Database,Statement} from './database';
import {appointmentGuard,settingsGuard,clearGuard} from './guards';
import {appointmentInput,filterSchema,patientInput,settingsSchema,slotsFor,clinicDate,clinicTime,type Filters} from './contracts';
import {z} from 'zod';
export class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
const joined=`SELECT a.id,a.patient_id AS "patientId",p.hn,p.name,p.dob,p.sex,p.version AS "patientVersion",a.date,a.time,a.arrival,a.service,a.followup,a.tags,a.status,a.seen,a.remarks,a.version,a.created_at AS "createdAt",a.updated_at AS "updatedAt" FROM appointments a JOIN patients p ON p.id=a.patient_id`;
function mapRow(r:any){return {...r,seen:!!r.seen,followup:!!r.followup,tags:JSON.parse(r.tags||'[]')}}
export async function settings(db:Database){const s=await db.prepare('SELECT open,close,capacity,version FROM clinic_settings WHERE id=1').first();if(s)return s;await db.prepare("INSERT INTO clinic_settings(id,open,close,capacity,version) VALUES(1,'10:00','16:00',1,1) ON CONFLICT(id) DO NOTHING").run();return settings(db)}
const literal=(s:string)=>'%'+s.replace(/[\\%_]/g,'\\$&')+'%';
export async function search(db:Database,raw:unknown,offset=0){const f=filterSchema.parse(raw);const where:string[]=[];const values:(string|number)[]=[];const add=(sql:string,...v:(string|number)[])=>{where.push(sql);values.push(...v)};
 if(f.dateFrom)add('a.date>=?',f.dateFrom);if(f.dateTo)add('a.date<=?',f.dateTo);const tc=f.timeField==='arrival'?'a.arrival':'a.time';if(f.timeFrom)add(`${tc}>=?`,f.timeFrom);if(f.timeTo)add(`${tc}<=?`,f.timeTo);
 if(f.statuses.length)add(`a.status IN (${f.statuses.map(()=>'?').join(',')})`,...f.statuses);else if(!f.includeCancelled)add("a.status NOT IN ('cancelled','no_show')");
 if(f.seen!==undefined)add('a.seen=?',Number(f.seen));if(f.followup!==undefined)add('a.followup=?',Number(f.followup));if(f.arrived!==undefined)where.push(f.arrived?'a.arrival IS NOT NULL':'a.arrival IS NULL');
 if(f.hn)add('p.hn=?',f.hn.toUpperCase().trim());if(f.text)add("(p.hn ILIKE ? ESCAPE '\\' OR p.name ILIKE ? ESCAPE '\\' OR a.service ILIKE ? ESCAPE '\\' OR a.remarks ILIKE ? ESCAPE '\\')",...Array(4).fill(literal(f.text)));if(f.remarks)add("a.remarks ILIKE ? ESCAPE '\\'",literal(f.remarks));
 if(f.casesAny.length)add(`(${f.casesAny.map(()=>"(a.service ILIKE ? ESCAPE '\\' OR EXISTS(SELECT 1 FROM jsonb_array_elements_text(a.tags::jsonb) AS tag(value) WHERE value ILIKE ? ESCAPE '\\'))").join(' OR ')})`,...f.casesAny.flatMap(t=>[literal(t),literal(t)]));
 if(f.waitingMinutes!==undefined){add("a.status='waiting' AND a.date=? AND a.arrival IS NOT NULL AND (CAST(substr(?,1,2) AS INTEGER)*60+CAST(substr(?,4,2) AS INTEGER)-CAST(substr(a.arrival,1,2) AS INTEGER)*60-CAST(substr(a.arrival,4,2) AS INTEGER))>=?",clinicDate(),clinicTime(),clinicTime(),f.waitingMinutes)}
 const suffix=where.length?' WHERE '+where.join(' AND '):'';const data=await db.batch([db.prepare(joined+suffix+' ORDER BY a.date,a.time,p.name LIMIT 100 OFFSET ?').bind(...values,offset),db.prepare('SELECT COUNT(*) AS total FROM appointments a JOIN patients p ON p.id=a.patient_id'+suffix).bind(...values)]);return {rows:data[0].results.map(mapRow),total:(data[1].results[0] as any).total,offset,filters:f};
}
export async function getAppointment(db:Database,id:string){const row=await db.prepare(joined+' WHERE a.id=?').bind(id).first();if(!row)throw new HttpError(404,'Appointment not found');return mapRow(row)}
function eventStmt(db:Database,eventId:string,type:string,id:string,actor:string,now:string,payload:object){return db.prepare('INSERT INTO events(id,type,entity_id,actor,at,payload) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM appointments WHERE id=? AND last_event=?)').bind(eventId,type,id,actor,now,JSON.stringify(payload),id,eventId)}
function validateVisit(a:z.infer<typeof appointmentInput>){if(a.status==='no_show'&&(a.arrival||a.seen))throw new HttpError(400,'A patient who has arrived cannot be marked as a no-show.');if(a.status==='booked'&&(a.arrival||a.seen))throw new HttpError(400,'An arrived patient should be waiting, diagnosed, or ready to go home.');if(['waiting','diagnosed','home'].includes(a.status)&&!a.arrival)throw new HttpError(400,'Record the arrival time first.');if(['diagnosed','home'].includes(a.status)&&!a.seen)throw new HttpError(400,'Mark the patient as seen by the doctor first.');if(a.status==='waiting'&&a.seen)throw new HttpError(400,'A patient already seen by the doctor cannot be marked waiting.');if(a.arrival&&a.date>clinicDate())throw new HttpError(400,'Arrival cannot be recorded for a future appointment.');}
export async function saveAppointment(db:Database,body:unknown,actor:string,id?:string){
 const a=appointmentInput.parse(body);validateVisit(a);
 const now=new Date().toISOString(),eventId=crypto.randomUUID();
 const configQuery=db.prepare('SELECT open,close,capacity,version FROM clinic_settings WHERE id=1');
 if(id){
  if(!a.version)throw new HttpError(400,'Version is required');
  const preflight=await db.batch([configQuery,db.prepare(joined+' WHERE a.id=?').bind(id)]);
  const config:any=preflight[0].results[0]||{open:'10:00',close:'16:00',capacity:1,version:1};
  if(!preflight[1].results[0])throw new HttpError(404,'Appointment not found');
  const current=mapRow(preflight[1].results[0]);
  if((current.date!==a.date||current.time!==a.time)&&!slotsFor(config).includes(a.time))throw new HttpError(400,'Choose a half-hour slot within clinic hours.');
  if(current.version!==a.version)throw new HttpError(409,'This visit changed on another device. Reload it before saving.');
  if(a.patient||a.patientId!==current.patientId)throw new HttpError(400,'Patient identity cannot be replaced through a booking.');
  const result=await db.batch([
   appointmentGuard(db,eventId,a,id),
   db.prepare('UPDATE appointments SET date=?,time=?,arrival=?,service=?,followup=?,tags=?,status=?,seen=?,remarks=?,version=version+1,updated_at=?,last_event=? WHERE id=? AND version=?').bind(a.date,a.time,a.arrival,a.service,Number(a.followup),JSON.stringify(a.tags),a.status,Number(a.seen),a.remarks,now,eventId,id,a.version),
   eventStmt(db,eventId,a.status!==current.status?'appointment.status_changed':'appointment.updated',id,actor,now,{before:current,after:a}),clearGuard(db,eventId),
   db.prepare(joined+' WHERE a.id=?').bind(id)
  ]);
  if(!result[1].meta.changes)throw new HttpError(409,'This visit changed on another device. Reload it before saving.');
  return mapRow(result[result.length-1].results[0]);
 }
 if((!!a.patientId)===(!!a.patient))throw new HttpError(400,'Select an existing patient or provide one new patient.');
 const preflight=await db.batch([configQuery,db.prepare(joined+' WHERE a.request_id=?').bind(a.requestId),...(a.patientId?[db.prepare('SELECT id FROM patients WHERE id=?').bind(a.patientId)]:[])]);
 // Retries return the prior committed record even if clinic hours changed later.
 if(preflight[1].results[0])return checkReplayRow(mapRow(preflight[1].results[0]),a);
 const config:any=preflight[0].results[0]||{open:'10:00',close:'16:00',capacity:1,version:1};
 if(!slotsFor(config).includes(a.time))throw new HttpError(400,'Choose a half-hour slot within clinic hours.');
 if(a.patientId&&!preflight[2].results[0])throw new HttpError(404,'Patient not found');
 const patientId=a.patientId||crypto.randomUUID(),newId=crypto.randomUUID();
 const statements:Statement[]=[appointmentGuard(db,eventId,a)];
 if(a.patient){const p=patientInput.parse(a.patient);statements.push(db.prepare('INSERT INTO patients(id,hn,name,dob,sex,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').bind(patientId,p.hn.toUpperCase(),p.name,p.dob,p.sex,now,now))}
 statements.push(db.prepare('INSERT INTO appointments(id,patient_id,date,time,arrival,service,followup,tags,status,seen,remarks,created_at,updated_at,last_event,request_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(newId,patientId,a.date,a.time,a.arrival,a.service,Number(a.followup),JSON.stringify(a.tags),a.status,Number(a.seen),a.remarks,now,now,eventId,a.requestId),eventStmt(db,eventId,'appointment.created',newId,actor,now,{patientId,date:a.date,time:a.time}),clearGuard(db,eventId),db.prepare(joined+' WHERE a.id=?').bind(newId));
 try{const result=await db.batch(statements);return mapRow(result[result.length-1].results[0])}
 catch(error:any){const retry=await db.prepare(joined+' WHERE a.request_id=?').bind(a.requestId).first();if(retry)return checkReplayRow(mapRow(retry),a);throw error}
}
export async function updatePatient(db:Database,id:string,body:unknown,actor:string){const input=z.object({patient:patientInput,version:z.number().int().positive()}).strict().parse(body);const p=input.patient;const now=new Date().toISOString();const previous:any=await db.prepare('SELECT * FROM patients WHERE id=?').bind(id).first();if(!previous)throw new HttpError(404,'Patient not found');if(previous.version!==input.version)throw new HttpError(409,'Patient details changed. Reload before editing.');const eventId=crypto.randomUUID();const result=await db.batch([db.prepare('UPDATE patients SET hn=?,name=?,dob=?,sex=?,version=version+1,updated_at=?,last_event=? WHERE id=? AND version=?').bind(p.hn.toUpperCase(),p.name,p.dob,p.sex,now,eventId,id,input.version),db.prepare('INSERT INTO events(id,type,entity_id,actor,at,payload) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM patients WHERE id=? AND last_event=?)').bind(eventId,'patient.updated',id,actor,now,JSON.stringify({before:previous,after:p}),id,eventId)]);if(!result[0].meta.changes)throw new HttpError(409,'Patient details changed. Reload before editing.');return db.prepare('SELECT * FROM patients WHERE id=?').bind(id).first()}
export async function saveSettings(db:Database,body:unknown,actor:string){const s=settingsSchema.parse(body);const count:any=await db.prepare("SELECT COUNT(*) AS n FROM appointments WHERE status NOT IN ('cancelled','no_show') GROUP BY date,time HAVING COUNT(*)>? LIMIT 1").bind(s.capacity).first();if(count)throw new HttpError(409,'Some slots have more bookings than this capacity. Move those bookings first.');const outside=await db.prepare("SELECT id FROM appointments WHERE status NOT IN ('cancelled','no_show') AND date>=? AND (time<? OR time>=?) LIMIT 1").bind(clinicDate(),s.open,s.close).first();if(outside)throw new HttpError(409,'Upcoming bookings fall outside these hours. Move those bookings first.');const now=new Date().toISOString();const eventId=crypto.randomUUID();const rs=await db.batch([settingsGuard(db,eventId,s,clinicDate()),db.prepare('UPDATE clinic_settings SET open=?,close=?,capacity=?,version=version+1,last_event=? WHERE id=1 AND version=?').bind(s.open,s.close,s.capacity,eventId,s.version),db.prepare('INSERT INTO events(id,type,entity_id,actor,at,payload) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM clinic_settings WHERE id=1 AND last_event=?)').bind(eventId,'settings.updated','clinic',actor,now,JSON.stringify(s),eventId),clearGuard(db,eventId)]);if(!rs[1].meta.changes)throw new HttpError(409,'Settings changed. Reload before saving.');return settings(db)}
export async function seedSamples(db:Database,actor:string){await settings(db);if(await db.prepare('SELECT id FROM patients LIMIT 1').first())throw new HttpError(409,'Examples can only be added to an empty clinic.');const rows=[['DEMO-001','Mali Somchai','1990-03-12','Female','10:00','09:50','Follow-up consultation',true,'home',true,'Wheelchair assistance requested',['Mobility']],['DEMO-002','Narin Chaiyaporn','1984-08-21','Male','10:30','10:25','General consultation',false,'diagnosed',true,'Accompanied by daughter',['General']],['DEMO-003','Pim Srisuk','1998-11-06','Female','11:00','10:55','Wound care',true,'waiting',false,'Follow-up dressing',['Wound care']],['DEMO-004','Anan Wattanakul','1979-05-17','Male','12:00',null,'General consultation',false,'booked',false,'Thai interpreter requested',['General']]];
 const now=new Date().toISOString(),statements:Statement[]=[];for(const [hn,name,dob,sex,time,arrival,service,followup,status,seen,remarks,tags] of rows){const p=crypto.randomUUID(),id=crypto.randomUUID(),event=crypto.randomUUID();statements.push(appointmentGuard(db,event,{date:clinicDate(),time:String(time),status:String(status)}),db.prepare('INSERT INTO patients(id,hn,name,dob,sex,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').bind(p,hn,name,dob,sex,now,now),db.prepare('INSERT INTO appointments(id,patient_id,date,time,arrival,service,followup,tags,status,seen,remarks,created_at,updated_at,last_event,request_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,p,clinicDate(),time,arrival,service,Number(followup),JSON.stringify(tags),status,Number(seen),remarks,now,now,event,crypto.randomUUID()),eventStmt(db,event,'appointment.example_created',id,actor,now,{example:true}),clearGuard(db,event))}await db.batch(statements);return {added:4}}

function checkReplayRow(r:any,a:z.infer<typeof appointmentInput>){const equal=['date','time','arrival','service','followup','status','seen','remarks'].every(k=>(r as any)[k]===(a as any)[k])&&JSON.stringify(r.tags)===JSON.stringify(a.tags)&&(a.patientId?r.patientId===a.patientId:a.patient&&r.hn===a.patient.hn.toUpperCase()&&r.name===a.patient.name&&r.dob===a.patient.dob&&r.sex===a.patient.sex);if(!equal)throw new HttpError(409,'This save request was already completed with different details. Close the form and check the saved booking.');return r}
